apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  template:
    spec:
      containers:
      - name: application
        envFrom:
        - configMapRef:
            name: configmap-env
        - secretRef:
            name: secret-env
