apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  template:
    spec:
      containers:
      - name: application
        envFrom:
        - $patch: merge
          secretRef:
            name: secret-env
