apiVersion: apps/v1
kind: Deployment
metadata:
  name: APP_NAME
  labels:
    app.kubernetes.io/name: APP_NAME
    app.kubernetes.io/instance: APP_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: APP_NAME
      app.kubernetes.io/instance: APP_NAME
  template:
    metadata:
      labels:
        app.kubernetes.io/name: APP_NAME
        app.kubernetes.io/instance: APP_NAME
    spec:
      containers:
        - name: APP_NAME
          image: $(IMAGE_REGISTRY_URL_SIT):abc
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            timeoutSeconds: 10
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            timeoutSeconds: 10
            initialDelaySeconds: 10
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 400m
              memory: 64Mi

