apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  template:
    spec:
      volumes:
      - name: secret-file
        configMap:
          name: secret-file
      containers:
      - name: application
        volumeMounts:
        - name: secret-file
          mountPath: /app/secret/
